public class __M$Effect_Aff_AVar {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Effect.Aff.AVar"); }
    };


public static final Object tryTake = __init$tryTake();
    private static Object __init$tryTake() { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Effect_Aff._liftEffect))).apply(__M$Effect_AVar.tryTake); }
public static final Object tryRead = __init$tryRead();
    private static Object __init$tryRead() { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Effect_Aff._liftEffect))).apply(__M$Effect_AVar.tryRead); }
public static final Object tryPut = __init$tryPut();
    private static Object __init$tryPut() { return (java.util.function.Function<Object, Object>) (value_0$r0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Effect_Aff._liftEffect))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_AVar.tryPut)).apply(value_0$r0)); }; }
public static final Object take = __init$take();
    private static Object __init$take() { return (java.util.function.Function<Object, Object>) (avar_0$r0) -> { return ((java.util.function.Function<Object, Object>) (__M$Effect_Aff.makeAff)).apply((java.util.function.Function<Object, Object>) (k_1$r1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_2$r2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Effect_AVar._takeVar)).apply(__M$Effect_AVar.ffiUtil))).apply(avar_0$r0))).apply(k_1$r1); Object c_3$r3 = ((java.util.function.Supplier) (Object)(__local_var_2$r2)).get(); return ((java.util.function.Function<Object, Object>) (__M$Effect_Aff.effectCanceler)).apply(c_3$r3); } }); }); }; }
public static final Object status = __init$status();
    private static Object __init$status() { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Effect_Aff._liftEffect))).apply(__M$Effect_AVar.status); }
public static final Object read = __init$read();
    private static Object __init$read() { return (java.util.function.Function<Object, Object>) (avar_0$r0) -> { return ((java.util.function.Function<Object, Object>) (__M$Effect_Aff.makeAff)).apply((java.util.function.Function<Object, Object>) (k_1$r1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_2$r2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Effect_AVar._readVar)).apply(__M$Effect_AVar.ffiUtil))).apply(avar_0$r0))).apply(k_1$r1); Object c_3$r3 = ((java.util.function.Supplier) (Object)(__local_var_2$r2)).get(); return ((java.util.function.Function<Object, Object>) (__M$Effect_Aff.effectCanceler)).apply(c_3$r3); } }); }); }; }
public static final Object put = __init$put();
    private static Object __init$put() { return (java.util.function.Function<Object, Object>) (value_0$r0) -> { return (java.util.function.Function<Object, Object>) (avar_1$r1) -> { return ((java.util.function.Function<Object, Object>) (__M$Effect_Aff.makeAff)).apply((java.util.function.Function<Object, Object>) (k_2$r2) -> { return (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_3$r3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Effect_AVar._putVar)).apply(__M$Effect_AVar.ffiUtil))).apply(value_0$r0))).apply(avar_1$r1))).apply(k_2$r2); Object c_4$r4 = ((java.util.function.Supplier) (Object)(__local_var_3$r3)).get(); return ((java.util.function.Function<Object, Object>) (__M$Effect_Aff.effectCanceler)).apply(c_4$r4); } }); }); }; }; }
public static final Object $new = __init$$new();
    private static Object __init$$new() { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Effect_Aff._liftEffect))).apply(__M$Effect_AVar.$new); }
public static final Object kill = __init$kill();
    private static Object __init$kill() { return (java.util.function.Function<Object, Object>) (error_0$r0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(__M$Effect_Aff._liftEffect))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_AVar.kill)).apply(error_0$r0)); }; }
public static final Object empty = __init$empty();
    private static Object __init$empty() { return ((java.util.function.Function<Object, Object>) (__M$Effect_Aff._liftEffect)).apply(__M$Effect_AVar.empty); }
}
