public class __M$Control_Parallel {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Control.Parallel"); }
    };


public static final Object parTraverse_ = __init$parTraverse_();
    private static Object __init$parTraverse_() { return (java.util.function.Function<Object, Object>) (dictParallel_0$r0) -> { Object sequential_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Control_Parallel_Class.sequential)).apply(dictParallel_0$r0); Object parallel_2$r2 = ((java.util.function.Function<Object, Object>) (__M$Control_Parallel_Class.parallel)).apply(dictParallel_0$r0); return (java.util.function.Function<Object, Object>) (dictApplicative_3$r3) -> { return (java.util.function.Function<Object, Object>) (dictFoldable_4$r4) -> { return (java.util.function.Function<Object, Object>) (f_5$r5) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(sequential_1$r1))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Foldable.traverse_)).apply(dictApplicative_3$r3))).apply(dictFoldable_4$r4))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(parallel_2$r2))).apply(f_5$r5))); }; }; }; }; }
public static final Object parTraverse = __init$parTraverse();
    private static Object __init$parTraverse() { return (java.util.function.Function<Object, Object>) (dictParallel_0$r0) -> { Object sequential_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Control_Parallel_Class.sequential)).apply(dictParallel_0$r0); Object parallel_2$r2 = ((java.util.function.Function<Object, Object>) (__M$Control_Parallel_Class.parallel)).apply(dictParallel_0$r0); return (java.util.function.Function<Object, Object>) (dictApplicative_3$r3) -> { return (java.util.function.Function<Object, Object>) (dictTraversable_4$r4) -> { return (java.util.function.Function<Object, Object>) (f_5$r5) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(sequential_1$r1))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictTraversable_4$r4).get("traverse"))).apply(dictApplicative_3$r3))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(parallel_2$r2))).apply(f_5$r5))); }; }; }; }; }
public static final Object parSequence_ = __init$parSequence_();
    private static Object __init$parSequence_() { return (java.util.function.Function<Object, Object>) (dictParallel_0$r0) -> { return (java.util.function.Function<Object, Object>) (dictApplicative_1$r1) -> { return (java.util.function.Function<Object, Object>) (dictFoldable_2$r2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Parallel.parTraverse_)).apply(dictParallel_0$r0))).apply(dictApplicative_1$r1))).apply(dictFoldable_2$r2))).apply((java.util.function.Function<Object, Object>) (x_3$r3) -> { return x_3$r3; }); }; }; }; }
public static final Object parSequence = __init$parSequence();
    private static Object __init$parSequence() { return (java.util.function.Function<Object, Object>) (dictParallel_0$r0) -> { return (java.util.function.Function<Object, Object>) (dictApplicative_1$r1) -> { return (java.util.function.Function<Object, Object>) (dictTraversable_2$r2) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Parallel.parTraverse)).apply(dictParallel_0$r0))).apply(dictApplicative_1$r1))).apply(dictTraversable_2$r2))).apply((java.util.function.Function<Object, Object>) (x_3$r3) -> { return x_3$r3; }); }; }; }; }
public static final Object parOneOfMap = __init$parOneOfMap();
    private static Object __init$parOneOfMap() { return (java.util.function.Function<Object, Object>) (dictParallel_0$r0) -> { Object sequential_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Control_Parallel_Class.sequential)).apply(dictParallel_0$r0); Object parallel_2$r2 = ((java.util.function.Function<Object, Object>) (__M$Control_Parallel_Class.parallel)).apply(dictParallel_0$r0); return (java.util.function.Function<Object, Object>) (dictAlternative_3$r3) -> { Object Plus1_4$r4 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictAlternative_3$r3).get("Plus1"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (dictFoldable_5$r5) -> { return (java.util.function.Function<Object, Object>) (dictFunctor_6$r6) -> { return (java.util.function.Function<Object, Object>) (f_7$r7) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(sequential_1$r1))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Foldable.oneOfMap)).apply(dictFoldable_5$r5))).apply(Plus1_4$r4))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(parallel_2$r2))).apply(f_7$r7))); }; }; }; }; }; }
public static final Object parOneOf = __init$parOneOf();
    private static Object __init$parOneOf() { return (java.util.function.Function<Object, Object>) (dictParallel_0$r0) -> { Object sequential_1$r1 = ((java.util.function.Function<Object, Object>) (__M$Control_Parallel_Class.sequential)).apply(dictParallel_0$r0); Object parallel_2$r2 = ((java.util.function.Function<Object, Object>) (__M$Control_Parallel_Class.parallel)).apply(dictParallel_0$r0); return (java.util.function.Function<Object, Object>) (dictAlternative_3$r3) -> { Object Plus1_4$r4 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictAlternative_3$r3).get("Plus1"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (dictFoldable_5$r5) -> { return (java.util.function.Function<Object, Object>) (dictFunctor_6$r6) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(sequential_1$r1))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Data_Foldable.oneOfMap)).apply(dictFoldable_5$r5))).apply(Plus1_4$r4))).apply(parallel_2$r2)); }; }; }; }; }
public static final Object parApply = __init$parApply();
    private static Object __init$parApply() { return (java.util.function.Function<Object, Object>) (dictParallel_0$r0) -> { Object Apply1_1$r1 = ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictParallel_0$r0).get("Apply1"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (mf_2$r2) -> { return (java.util.function.Function<Object, Object>) (ma_3$r3) -> { return ((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictParallel_0$r0).get("sequential"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) Apply1_1$r1).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictParallel_0$r0).get("parallel"))).apply(mf_2$r2)))).apply(((java.util.function.Function<Object, Object>) (((java.util.Map<String, Object>) dictParallel_0$r0).get("parallel"))).apply(ma_3$r3))); }; }; }; }
}
