public class __M$Effect_Aff_AVar {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { throw new UnsupportedOperationException("Missing Java FFI in Effect.Aff.AVar"); }
    };


public static final Object tryTake = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(__M$Effect_Aff.monadEffectAff)))).apply(__M$Effect_AVar.tryTake);
public static final Object tryRead = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(__M$Effect_Aff.monadEffectAff)))).apply(__M$Effect_AVar.tryRead);
public static final Object tryPut = (java.util.function.Function<Object, Object>) (value_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(__M$Effect_Aff.monadEffectAff)))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_AVar.tryPut)).apply(value_0_i0)); };
public static final Object take = (java.util.function.Function<Object, Object>) (avar_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Effect_Aff.makeAff)).apply((java.util.function.Function<Object, Object>) (k_1_i1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_2_i2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Effect_AVar._takeVar)).apply(__M$Effect_AVar.ffiUtil))).apply(avar_0_i0))).apply(k_1_i1); Object c_3_i3 = ((java.util.function.Supplier) (Object)(__local_var_2_i2)).get(); return ((java.util.function.Function<Object, Object>) (__M$Effect_Aff.effectCanceler)).apply(c_3_i3); } }); }); };
public static final Object status = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(__M$Effect_Aff.monadEffectAff)))).apply(__M$Effect_AVar.status);
public static final Object read = (java.util.function.Function<Object, Object>) (avar_0_i0) -> { return ((java.util.function.Function<Object, Object>) (__M$Effect_Aff.makeAff)).apply((java.util.function.Function<Object, Object>) (k_1_i1) -> { return (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_2_i2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Effect_AVar._readVar)).apply(__M$Effect_AVar.ffiUtil))).apply(avar_0_i0))).apply(k_1_i1); Object c_3_i3 = ((java.util.function.Supplier) (Object)(__local_var_2_i2)).get(); return ((java.util.function.Function<Object, Object>) (__M$Effect_Aff.effectCanceler)).apply(c_3_i3); } }); }); };
public static final Object put = (java.util.function.Function<Object, Object>) (value_0_i0) -> { return (java.util.function.Function<Object, Object>) (avar_1_i1) -> { return ((java.util.function.Function<Object, Object>) (__M$Effect_Aff.makeAff)).apply((java.util.function.Function<Object, Object>) (k_2_i2) -> { return (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_3_i3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Effect_AVar._putVar)).apply(__M$Effect_AVar.ffiUtil))).apply(value_0_i0))).apply(avar_1_i1))).apply(k_2_i2); Object c_4_i4 = ((java.util.function.Supplier) (Object)(__local_var_3_i3)).get(); return ((java.util.function.Function<Object, Object>) (__M$Effect_Aff.effectCanceler)).apply(c_4_i4); } }); }); }; };
public static final Object $new = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(__M$Effect_Aff.monadEffectAff)))).apply(__M$Effect_AVar.$new);
public static final Object kill = (java.util.function.Function<Object, Object>) (error_0_i0) -> { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (__M$Control_Semigroupoid.compose)).apply(__M$Control_Semigroupoid.semigroupoidFn))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_Class.liftEffect)).apply(__M$Effect_Aff.monadEffectAff)))).apply(((java.util.function.Function<Object, Object>) (__M$Effect_AVar.kill)).apply(error_0_i0)); };
public static final Object empty = ((java.util.function.Function<Object, Object>) (__M$Effect_Aff._liftEffect)).apply(__M$Effect_AVar.empty);
}
